<?php
/**
 * Synapse (db_webtable) — Rental Expiry Sweep CLI (M3, plan/60 §4.6)
 *
 * Manual/operator-invoked maintenance tool (NOT cron — owner constraint).
 * Closes expired GPU rental contracts: user_rentals.status 'active' →
 * 'completed' where expired_at <= now (WIB). Idempotent: the guarded
 * WHERE only matches rows still 'active', so re-runs are no-ops.
 *
 *   --dry-run   (default) count + sample matching rows, writes nothing
 *   --apply     flip rows inside ONE transaction, prints flipped count
 *   --help|-h   usage
 *
 * WIB discipline: date_default_timezone_set('Asia/Jakarta') + MySQL
 * session `SET time_zone = '+07:00'` (same pin as MY_Controller); the
 * comparison bound param is generated by PHP (konvensi plan/50 — MySQL
 * server NOW() TIDAK dipakai). Credentials parsed from
 * application/config/database.php (CI3), same as backfill_withdrawal_fees.php.
 * Exit codes: 0 = clean, 1 = pre-flight failure, 2 = apply failure.
 */

define('BASEPATH', 'cli-expire-rentals-runner');
define('ENVIRONMENT', 'development');

error_reporting(E_ALL);
ini_set('display_errors', '1');
mysqli_report(MYSQLI_REPORT_ERROR | MYSQLI_REPORT_STRICT);

if (date_default_timezone_get() !== 'Asia/Jakarta') {
    date_default_timezone_set('Asia/Jakarta');
}

$ROOT = dirname(__DIR__);
const SWEEP_DB = 'db_webtable';

$args   = $argv ?: [];
$apply  = in_array('--apply', $args, true);
$dryRun = !$apply;
if (in_array('--help', $args, true) || in_array('-h', $args, true)) {
    echo "Usage: php scripts/expire_rentals.php [--dry-run|--apply] [--help]\n"
       . "  --dry-run  (default) count + sample rows matching expiry, writes nothing\n"
       . "  --apply    close expired contracts (active -> completed) in ONE transaction\n";
    exit(0);
}

// ---------------------------------------------------------------- config
function load_db_config($file)
{
    if (!is_file($file)) return null;
    include $file;
    return isset($db['default']) ? $db['default'] : null;
}

$db = load_db_config($ROOT . '/application/config/database.php');
if (!$db) {
    fwrite(STDERR, "[FATAL] Cannot read DB credentials from application/config/database.php\n");
    exit(1);
}
$host = $db['hostname'] === 'localhost' ? '127.0.0.1' : $db['hostname'];

// ---------------------------------------------------------------- connect
try {
    $m = new mysqli($host, $db['username'], $db['password'], $db['database'], 3306);
    $m->set_charset('utf8mb4');
    // WIB session pin — identik dengan MY_Controller (SET time_zone '+07:00').
    $m->query("SET time_zone = '+07:00'");
} catch (mysqli_sql_exception $e) {
    fwrite(STDERR, "[FATAL] Cannot connect to {$db['database']}: " . $e->getMessage() . "\n");
    exit(1);
}
echo "== Rental expiry sweep (M3) ==\n";
echo "Server: {$m->server_info}  DB: {$db['database']}\n\n";

// ---------------------------------------------------------------- pre-flight
$q = $m->query("SHOW TABLES LIKE 'user_rentals'");
if (!$q || $q->num_rows === 0) {
    fwrite(STDERR, "[FATAL] Missing table: user_rentals\n");
    exit(1);
}
$q = $m->query("SELECT 1 FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = '" . $m->real_escape_string(SWEEP_DB) . "'
                  AND TABLE_NAME   = 'user_rentals'
                  AND COLUMN_NAME  = 'expired_at'");
if (!$q || $q->num_rows === 0) {
    fwrite(STDERR, "[FATAL] user_rentals.expired_at missing — schema out of sync\n");
    exit(1);
}
// Index health check (informational — M3 plan/60 §5).
$q = $m->query("SELECT INDEX_NAME FROM information_schema.STATISTICS
                WHERE TABLE_SCHEMA = '" . $m->real_escape_string(SWEEP_DB) . "'
                  AND TABLE_NAME = 'user_rentals'
                  AND INDEX_NAME IN ('idx_user_status_expired','idx_status_expired')
                GROUP BY INDEX_NAME");
$have = [];
while ($r = $q->fetch_row()) { $have[] = $r[0]; }
foreach (['idx_user_status_expired', 'idx_status_expired'] as $idx) {
    if (!in_array($idx, $have, true)) {
        echo "  [WARN] index {$idx} missing — apply plan/60 §4.5 ALTER for sub-millisecond sweeps.\n";
    }
}

$now = date('Y-m-d H:i:s'); // WIB via PHP (konvensi plan/50)
echo "Reference WIB now: {$now}\n\n";

// ---------------------------------------------------------------- dry-run scan
$stmt = $m->prepare(
    "SELECT COUNT(*) AS cnt FROM user_rentals
      WHERE status = 'active' AND expired_at <= ?"
);
$stmt->bind_param('s', $now);
$stmt->execute();
$cnt = (int) $stmt->get_result()->fetch_assoc()['cnt'];
$stmt->close();

echo 'Expired-but-active contracts: ' . $cnt . "\n";

if ($dryRun) {
    if ($cnt > 0) {
        $stmt = $m->prepare(
            "SELECT id, user_id, product_id, expired_at, days_processed, total_days
               FROM user_rentals
              WHERE status = 'active' AND expired_at <= ?
              ORDER BY expired_at ASC
              LIMIT 25"
        );
        $stmt->bind_param('s', $now);
        $stmt->execute();
        $res = $stmt->get_result();
        while ($r = $res->fetch_assoc()) {
            printf("  #%-7d user=%-6d product=%-4d expired_at=%s days=%d/%d\n",
                   (int) $r['id'], (int) $r['user_id'], (int) $r['product_id'],
                   $r['expired_at'], (int) $r['days_processed'], (int) $r['total_days']);
        }
        $stmt->close();
        echo "\nDRY-RUN: no changes made. Run: php scripts/expire_rentals.php --apply\n";
    } else {
        echo "Nothing to expire — all contracts current.\n";
    }
    exit(0);
}

// ---------------------------------------------------------------- apply
if ($cnt === 0) {
    echo "Nothing to expire — all contracts current.\n";
    exit(0);
}

try {
    $m->begin_transaction();
    $stmt = $m->prepare(
        "UPDATE user_rentals
            SET status = 'completed'
          WHERE status = 'active' AND expired_at <= ?"
    );
    $stmt->bind_param('s', $now);
    $stmt->execute();
    $flipped = $stmt->affected_rows;
    $stmt->close();
    $m->commit();
} catch (mysqli_sql_exception $e) {
    if ($m->errno) { $m->rollback(); }
    fwrite(STDERR, "[FATAL] Apply failed: " . $e->getMessage() . "\n");
    exit(2);
}

echo "\nApplied: {$flipped} contract(s) closed (active -> completed).\n";

// ---------------------------------------------------------------- post-check
$stmt = $m->prepare(
    "SELECT COUNT(*) AS cnt FROM user_rentals
      WHERE status = 'active' AND expired_at <= ?"
);
$stmt->bind_param('s', $now);
$stmt->execute();
$left = (int) $stmt->get_result()->fetch_assoc()['cnt'];
$stmt->close();

if ($left !== 0) {
    fwrite(STDERR, "[FATAL] Post-apply check failed: {$left} expired-but-active rows remain.\n");
    exit(2);
}
echo "Post-check OK: 0 expired-but-active rows remain.\n";
echo "Idempotent: re-running this script is a no-op.\n";
exit(0);
